version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wisdompet
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres

  django:
    image: apoorvabhishek/wisdom-pet:1.0
    environment:
      USER_NAME: admin
      USER_PWD: admin
      HOST: postgres
      PORT: 5432
    ports:
      - "8000:8000"
    depends_on: 
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
    postgres: